version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio

    ports:
      - 9001:9001
      - 9000:9000
    command: [ "server", "/data", "--console-address", ":9001" ]
    networks:
      minio-network:
        aliases:
          - warehouse.minio 

  mc:
    depends_on:
      - minio
    image: minio/mc:RELEASE.2024-05-09T17-04-24Z
    container_name: mc
    entrypoint: |
      /bin/sh -c "
        until (/usr/bin/mc config host add minio http://minio:9000 admin password)
        do
          echo '...waiting...' && sleep 1;
        done;
        /usr/bin/mc rm -r --force minio/warehouse;
        /usr/bin/mc mb minio/warehouse;
        /usr/bin/mc policy set public minio/warehouse;
        tail -f /dev/null
      "
    environment:
      - AWS_ACCESS_KEY_ID=mykey
      - AWS_SECRET_ACCESS_KEY=mypswd
      - AWS_REGION=us-east-1
    networks:
      minio-network:


networks:
  minio-network:

